import type { Metadata } from 'next';
import React from 'react';
import '@/shared/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const Layout: React.FC = ({ children }: { children: React.ReactNode }) => (
    <html lang="en">
      <body>{children}</body>
    </html>
);

export default Layout;
